services:
  ollama:
    gpus: all
    environment:
      NVIDIA_VISIBLE_DEVICES: ${NVIDIA_VISIBLE_DEVICES}
      NVIDIA_DRIVER_CAPABILITIES: ${NVIDIA_DRIVER_CAPABILITIES}
      OLLAMA_FLASH_ATTENTION: ${OLLAMA_FLASH_ATTENTION}
      OLLAMA_NUM_PARALLEL: ${OLLAMA_NUM_PARALLEL}
      OLLAMA_MAX_LOADED_MODELS: ${OLLAMA_MAX_LOADED_MODELS}