#!/usr/bin/env python3

import argparse
import base64
import hashlib
import secrets
import sys
from pathlib import Path


def read_env_file(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip()
    return values


def resolve_env_path(env_file: Path, value: str) -> Path:
    candidate = Path(value)
    if candidate.is_absolute():
        return candidate
    return (env_file.parent / candidate).resolve()


def require_env_key(values: dict[str, str], key: str) -> str:
    value = values.get(key, "").strip()
    if not value:
        raise KeyError(f"Missing required key in env file: {key}")
    return value


def sha_htpasswd_line(username: str, password: str) -> str:
    digest = hashlib.sha1(password.encode("utf-8")).digest()
    encoded = base64.b64encode(digest).decode("ascii")
    return f"{username}:{{SHA}}{encoded}\n"


def ensure_parent(path: Path, dry_run: bool) -> None:
    if dry_run:
        return
    path.parent.mkdir(parents=True, exist_ok=True)


def read_text_secret(path: Path) -> str:
    return path.read_text(encoding="utf-8").strip()


def write_text_secret(path: Path, content: str, force: bool, dry_run: bool) -> bool:
    if path.exists() and not force:
        return False
    ensure_parent(path, dry_run)
    if not dry_run:
        path.write_text(content, encoding="utf-8")
    return True


def write_empty_file(path: Path, force: bool, dry_run: bool) -> bool:
    if path.exists() and not force:
        return False
    ensure_parent(path, dry_run)
    if not dry_run:
        path.write_bytes(b"")
    return True


def generated_librechat_env(values: dict[str, str]) -> str:
    public_url = values.get("LIBRECHAT_PUBLIC_URL", "http://localhost:3080").strip() or "http://localhost:3080"
    librechat_port = values.get("LIBRECHAT_PORT", "3080").strip() or "3080"
    rag_port = values.get("LIBRECHAT_RAG_PORT", "8000").strip() or "8000"
    ollama_port = values.get("OLLAMA_PORT", "11434").strip() or "11434"
    embeddings_model = values.get("LIBRECHAT_RAG_EMBEDDINGS_MODEL", "nomic-embed-text").strip() or "nomic-embed-text"
    db_name = "librechat_rag"
    db_user = "librechat_rag"
    db_password = secrets.token_urlsafe(32)

    lines = [
        "# Generated by scripts/bootstrap-secrets.py. Keep this file out of git.",
        "HOST=0.0.0.0",
        f"PORT={librechat_port}",
        f"DOMAIN_CLIENT={public_url}",
        f"DOMAIN_SERVER={public_url}",
        "NO_INDEX=true",
        "TRUST_PROXY=1",
        "CONFIG_PATH=/app/librechat.yaml",
        "APP_TITLE=AI Tunnel Chat",
        "HELP_AND_FAQ_URL=/",
        "ENDPOINTS=custom",
        "DEBUG_LOGGING=false",
        "DEBUG_CONSOLE=false",
        "CONSOLE_JSON=false",
        "",
        "MONGO_URI=mongodb://librechat-mongodb:27017/LibreChat",
        "SEARCH=true",
        "MEILI_HOST=http://librechat-meilisearch:7700",
        "MEILI_NO_ANALYTICS=true",
        f"MEILI_MASTER_KEY={secrets.token_urlsafe(48)}",
        "",
        f"RAG_API_URL=http://librechat-rag-api:{rag_port}",
        f"RAG_PORT={rag_port}",
        "RAG_HOST=0.0.0.0",
        "EMBEDDINGS_PROVIDER=ollama",
        f"OLLAMA_BASE_URL=http://ollama:{ollama_port}",
        f"EMBEDDINGS_MODEL={embeddings_model}",
        "",
        f"POSTGRES_DB={db_name}",
        f"POSTGRES_USER={db_user}",
        f"POSTGRES_PASSWORD={db_password}",
        "DB_HOST=librechat-vectordb",
        "DB_PORT=5432",
        f"DB_NAME={db_name}",
        f"DB_USER={db_user}",
        f"DB_PASSWORD={db_password}",
        "",
        "ALLOW_EMAIL_LOGIN=true",
        "ALLOW_REGISTRATION=true",
        "ALLOW_SOCIAL_LOGIN=false",
        "ALLOW_SOCIAL_REGISTRATION=false",
        "ALLOW_PASSWORD_RESET=false",
        "ALLOW_UNVERIFIED_EMAIL_LOGIN=true",
        "SESSION_EXPIRY=900000",
        "REFRESH_TOKEN_EXPIRY=604800000",
        f"JWT_SECRET={secrets.token_hex(32)}",
        f"JWT_REFRESH_SECRET={secrets.token_hex(32)}",
        "",
        f"CREDS_KEY={secrets.token_hex(32)}",
        f"CREDS_IV={secrets.token_hex(16)}",
        "",
        "OPENAI_API_KEY=",
        "ANTHROPIC_API_KEY=",
        "GOOGLE_KEY=",
    ]
    return "\n".join(lines) + "\n"


def generated_pubmed_mcp_env() -> str:
    lines = [
        "# Generated by scripts/bootstrap-secrets.py. Keep this file out of git.",
        "# NCBI_ADMIN_EMAIL is recommended for NCBI E-utilities requests.",
        "# NCBI_API_KEY is optional, but raises NCBI rate limits from 3 req/s to 10 req/s.",
        "# UNPAYWALL_EMAIL is optional and enables legal open-access full-text fallback by DOI.",
        "NCBI_ADMIN_EMAIL=",
        "NCBI_API_KEY=",
        "UNPAYWALL_EMAIL=",
        "NCBI_REQUEST_DELAY_MS=334",
        "NCBI_MAX_RETRIES=6",
        "NCBI_TIMEOUT_MS=30000",
        "NCBI_TOTAL_DEADLINE_MS=60000",
        "UNPAYWALL_TIMEOUT_MS=20000",
        "OTEL_ENABLED=false",
    ]
    return "\n".join(lines) + "\n"


def generated_deepseek_v4_env() -> str:
    lines = [
        "# Generated by scripts/bootstrap-secrets.py. Keep this file out of git.",
        "# HF_TOKEN is optional and is used only for downloading local model weights.",
        "# Do not place remote inference API keys here; DeepSeek V4 runs locally in this stack.",
        "HF_TOKEN=",
    ]
    return "\n".join(lines) + "\n"


def ensure_librechat_env(values: dict[str, str], env_path: Path, force: bool, dry_run: bool) -> None:
    librechat_env_value = values.get("LIBRECHAT_ENV_FILE", "").strip()
    if not librechat_env_value:
        return

    librechat_env_path = resolve_env_path(env_path, librechat_env_value)
    content = generated_librechat_env(values)
    written = write_text_secret(librechat_env_path, content, force, dry_run)
    print_result(
        "Generated LibreChat env file" if written else "Kept existing LibreChat env file",
        librechat_env_path,
    )
    if written:
        print("Create the first LibreChat admin before publishing the LibreChat Cloudflare route, then run scripts/lock-librechat-registration.py.")


def ensure_pubmed_mcp_env(values: dict[str, str], env_path: Path, force: bool, dry_run: bool) -> None:
    pubmed_env_value = values.get("PUBMED_MCP_ENV_FILE", "").strip()
    if not pubmed_env_value:
        return

    pubmed_env_path = resolve_env_path(env_path, pubmed_env_value)
    written = write_text_secret(pubmed_env_path, generated_pubmed_mcp_env(), force, dry_run)
    print_result(
        "Generated PubMed MCP env file" if written else "Kept existing PubMed MCP env file",
        pubmed_env_path,
    )
    if written:
        print("Populate NCBI_ADMIN_EMAIL and optionally NCBI_API_KEY / UNPAYWALL_EMAIL before heavy PubMed use.")


def ensure_deepseek_v4_env(values: dict[str, str], env_path: Path, force: bool, dry_run: bool) -> None:
    deepseek_v4_env_value = values.get("DEEPSEEK_V4_ENV_FILE", "../ai-tunnel-secrets/deepseek-v4.env").strip()

    deepseek_v4_env_path = resolve_env_path(env_path, deepseek_v4_env_value)
    written = write_text_secret(deepseek_v4_env_path, generated_deepseek_v4_env(), force, dry_run)
    print_result(
        "Generated DeepSeek V4 env file" if written else "Kept existing DeepSeek V4 env file",
        deepseek_v4_env_path,
    )
    if written:
        print("Populate HF_TOKEN only if the local DeepSeek V4 model download requires Hugging Face authentication.")


def print_result(action: str, path: Path) -> None:
    print(f"{action}: {path}")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Create local secret placeholders and generated Nginx secrets for this stack."
    )
    parser.add_argument("--env-file", default=".env")
    parser.add_argument("--admin-user", default="admin")
    parser.add_argument("--force", action="store_true")
    parser.add_argument("--dry-run", action="store_true")
    return parser


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()

    env_path = Path(args.env_file).resolve()
    if not env_path.exists():
        raise FileNotFoundError(f"Missing env file: {env_path}")

    values = read_env_file(env_path)
    secrets_dir_value = values.get("SECRETS_DIR", "").strip()
    if secrets_dir_value:
        secrets_dir = resolve_env_path(env_path, secrets_dir_value)
        if not args.dry_run:
            secrets_dir.mkdir(parents=True, exist_ok=True)
        print_result("Ensured secrets directory", secrets_dir)

    api_token_path = resolve_env_path(env_path, require_env_key(values, "NGINX_API_TOKEN_FILE"))
    htpasswd_path = resolve_env_path(env_path, require_env_key(values, "NGINX_BASIC_AUTH_FILE"))
    password_path = resolve_env_path(
        env_path,
        values.get("NGINX_BASIC_AUTH_PASSWORD_FILE", "../ai-tunnel-secrets/nginx-admin-password"),
    )
    cloudflare_token_path = resolve_env_path(env_path, require_env_key(values, "CF_TUNNEL_TOKEN_FILE"))

    api_token = secrets.token_urlsafe(48)
    api_token_written = write_text_secret(api_token_path, api_token + "\n", args.force, args.dry_run)
    print_result("Generated Nginx API token" if api_token_written else "Kept existing Nginx API token", api_token_path)

    generated_password = False
    if password_path.exists() and not args.force:
        admin_password = read_text_secret(password_path)
        if not admin_password:
            raise RuntimeError(f"Nginx admin password file is empty: {password_path}")
        print_result("Kept existing Nginx admin password file", password_path)
    else:
        admin_password = secrets.token_urlsafe(18)
        generated_password = True
        write_text_secret(password_path, admin_password + "\n", True, args.dry_run)
        print_result("Generated Nginx admin password file", password_path)

    htpasswd_line = sha_htpasswd_line(args.admin_user, admin_password)
    write_text_secret(htpasswd_path, htpasswd_line, True, args.dry_run)
    print_result("Updated Nginx basic auth file", htpasswd_path)
    if generated_password:
        print(f"Nginx admin username: {args.admin_user}")
        print(f"Nginx admin password: {admin_password}")
        print("The generated admin password is also stored in the configured password file.")
    else:
        print("Reused the existing Nginx admin password file to regenerate the htpasswd entry.")

    cloudflare_written = write_empty_file(cloudflare_token_path, args.force, args.dry_run)
    print_result(
        "Created empty Cloudflare tunnel token placeholder" if cloudflare_written else "Kept existing Cloudflare tunnel token file",
        cloudflare_token_path,
    )
    if cloudflare_written:
        print("Populate the Cloudflare tunnel token file with the real tunnel token before starting the tunnel profile.")

    ensure_librechat_env(values, env_path, args.force, args.dry_run)
    ensure_pubmed_mcp_env(values, env_path, args.force, args.dry_run)
    ensure_deepseek_v4_env(values, env_path, args.force, args.dry_run)

    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as exc:
        print(f"bootstrap-secrets error: {exc}", file=sys.stderr)
        raise SystemExit(1)
